name: users_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  http_apis_define:
    git:
      url: https://github.com/ObsidianXVI/Toolchain.git
      path: dart_tools/boilerplates/http_apis/define
  dart_firebase_admin: ^0.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
